FROM alpine:latest

RUN apk update && apk add firefox dbus openbox ttf-dejavu curl

RUN echo "exec openbox-session" > /root/.xinitrc

ENV URL=http://mc.wakinyan.eu:2568

CMD ["sh", "-c", "openbox & firefox --kiosk $URL"]
