FROM alpine:latest

RUN apk update && apk add firefox dbus openbox ttf-dejavu curl nginx

RUN mkdir -p /usr/share/nginx/html

COPY ./out /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/nginx.conf

RUN echo "exec openbox-session" > /root/.xinitrc

ENV URL=http://localhost

CMD ["/bin/sh", "-c", "nginx & openbox & firefox -kiosk $URL"]

