# Dockerfile
# Use the official NGINX image
FROM nginx:latest

# Copy custom NGINX config file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the HTML file to the default NGINX directory
COPY ./out/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80
