FROM alpine:latest

RUN apk update && apk add firefox dbus openbox ttf-dejavu curl nginx

RUN ln -sf /usr/share/zoneinfo/Europe/Prague /etc/localtime && \
    echo "Europe/Prague" > /etc/timezone

RUN mkdir -p /usr/share/nginx/html

COPY ./out /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/nginx.conf

RUN echo "exec openbox-session" > /root/.xinitrc

ENV URL=http://localhost

RUN echo $URL

CMD ["/bin/sh", "-c", "nginx & openbox & firefox --kiosk \"$URL\""]
